// README facts generator — anti-drift for hand-written repo surfaces.
//
// The generated docs stay current by construction; hand-written surfaces
// (README.md, CONTRIBUTING.md, the marketing site) drift because facts live
// in them as prose. This generator derives the volatile facts — version,
// MCP tool count, CLI command list — from the source of truth and emits a
// compact USM:FACTS block that smart-merges into README.md.
//
// Humans keep their prose; the facts stop rotting.

import fs from "node:fs";
import path from "node:path";
import type { GenerationResult } from "../types.js";
import { findAllUsmFiles } from "../index.js";
import { parseUsmFile } from "../parse.js";
import type { FeatureUsm } from "../types.js";

const FACTS_START = "<!-- USM:FACTS:START -->";
const FACTS_END = "<!-- USM:FACTS:END -->";

function readPackageVersion(): string {
  try {
    const pkgPath = path.resolve(process.cwd(), "package.json");
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8")) as { version?: string };
    return pkg.version || "0.0.0";
  } catch {
    return "0.0.0";
  }
}

/**
 * Derive the canonical facts from the repo itself:
 * - version from package.json
 * - CLI commands from feature specs carrying a `command` field
 * - MCP tools from specs under features/mcp/ carrying a `command` field
 */
export function deriveFacts(root: string): {
  version: string;
  cliCommands: string[];
  mcpTools: string[];
} {
  const version = readPackageVersion();
  const cliCommands = new Set<string>();
  const mcpTools = new Set<string>();

  // A spec's `command` field may bundle several names ("a, b, c") — e.g. the
  // write-tools spec covers four MCP tools. Split into individual names.
  const splitCommands = (raw: string): string[] =>
    raw.split(",").map((s) => s.trim()).filter(Boolean);

  for (const filePath of findAllUsmFiles(root)) {
    try {
      const parsed = parseUsmFile(filePath);
      if (parsed.$type !== "feature") continue;
      const feature = parsed as FeatureUsm;
      if (!feature.command) continue;
      // MCP tools follow the usm_ naming convention; anything else is a CLI
      // command documented in that spec.
      for (const name of splitCommands(feature.command)) {
        if (name.startsWith("usm_")) mcpTools.add(name);
        else cliCommands.add(name);
      }
    } catch {
      // skip unparseable
    }
  }

  // Built-in commands that exist without feature specs
  for (const always of ["init", "scan", "validate", "generate", "info", "mcp"]) {
    cliCommands.add(always);
  }

  return {
    version,
    cliCommands: [...cliCommands].sort(),
    mcpTools: [...mcpTools].sort(),
  };
}

/**
 * Render the facts block (markdown, self-describing).
 */
export function renderFactsBlock(facts: { version: string; cliCommands: string[]; mcpTools: string[] }): string {
  const lines: string[] = [];
  lines.push(`> **Current release:** \`v${facts.version}\` · **CLI commands:** ${facts.cliCommands.map((c) => `\`${c}\``).join(", ")} · **MCP tools:** ${facts.mcpTools.length} (${facts.mcpTools.map((t) => `\`${t}\``).join(", ")})`);
  lines.push(">");
  lines.push("> *Auto-generated by `usm generate --only readme-facts` — edit the source of truth, not this block.*");
  return lines.join("\n");
}

/**
 * Smart-merge the facts block into an existing markdown file, or return the
 * block alone when the file doesn't exist yet.
 */
export function mergeFactsInto(content: string | null, factsBlock: string): string {
  if (content === null) {
    return `${FACTS_START}\n${factsBlock}\n${FACTS_END}\n`;
  }
  const startIndex = content.indexOf(FACTS_START);
  const endIndex = content.indexOf(FACTS_END);
  if (startIndex !== -1 && endIndex !== -1) {
    return content.slice(0, startIndex + FACTS_START.length) + "\n" + factsBlock + "\n" + content.slice(endIndex);
  }
  // No markers — insert after the first H1 heading (before badges/prose body)
  const lines = content.split("\n");
  const h1Index = lines.findIndex((l) => /^#\s+/.test(l));
  if (h1Index !== -1) {
    lines.splice(h1Index + 1, 0, "", FACTS_START, factsBlock, FACTS_END, "");
    return lines.join("\n");
  }
  return `${FACTS_START}\n${factsBlock}\n${FACTS_END}\n\n${content}`;
}

/**
 * Generate the README facts block — writes README.md in place (smart-merged).
 */
export function generateReadmeFacts(root: string): GenerationResult {
  const facts = deriveFacts(root);
  const block = renderFactsBlock(facts);
  const readmePath = path.join(root, "README.md");
  const existing = fs.existsSync(readmePath) ? fs.readFileSync(readmePath, "utf-8") : null;
  return {
    outputs: [{
      path: readmePath,
      content: mergeFactsInto(existing, block),
    }],
  };
}
