// Smart merge — preserve human-edited fields when re-scanning existing .usm files

import yaml from "js-yaml";
import type { SmartMergeResult } from "./types.js";
import { PRESERVE_FIELDS, UPDATE_FIELDS, MERGE_FIELDS } from "./types.js";

/**
 * Check if a field value looks like a default/generated placeholder.
 * Used to decide whether to preserve or overwrite.
 */
export function isDefaultContent(value: unknown): boolean {
  if (value === undefined || value === null) return true;

  if (typeof value === "string") {
    // Empty string
    if (value.trim() === "") return true;
    // Starts with "TODO: describe" — typical scan placeholder
    if (value.trim().startsWith("TODO: describe")) return true;
    // Starts with "TODO:" and is very short — likely placeholder
    if (value.trim().startsWith("TODO:") && value.trim().length < 50) return true;
    // Simple "name — kind" pattern generated by initConfig
    if (/^[a-z0-9-]+ — [a-z-]+ (service|shared package)$/.test(value.trim())) return true;
    return false;
  }

  if (Array.isArray(value)) {
    // Empty array
    if (value.length === 0) return true;
    // Array of TODO items
    if (value.every((item: unknown) => {
      if (typeof item === "string") return item.trim().startsWith("TODO:");
      if (typeof item === "object" && item !== null) {
        const obj = item as Record<string, unknown>;
        const purpose = obj.purpose as string | undefined;
        return purpose?.trim()?.startsWith("TODO: describe") ?? false;
      }
      return false;
    })) return true;
    return false;
  }

  if (typeof value === "object" && value !== null) {
    // Object with all empty values
    const obj = value as Record<string, unknown>;
    const values = Object.values(obj);
    if (values.length === 0) return true;
    if (values.every((v: unknown) => v === "" || v === undefined || v === null || v === 0)) return true;
    return false;
  }

  return false;
}

/**
 * Smart merge an existing .usm file content with newly generated content.
 *
 * Strategy:
 * - PRESERVE_FIELDS: Keep human-edited content, only overwrite if it's default/placeholder
 * - UPDATE_FIELDS: Always overwrite with scan-detected values (mechanical)
 * - MERGE_FIELDS: Additive merge — preserve existing keys, add new ones
 * - Other fields: Add if missing in generated, preserve if present in existing
 */
export function smartMerge(
  existingYaml: string,
  generated: Record<string, unknown>
): SmartMergeResult {
  const warnings: string[] = [];
  const preservedKeys: string[] = [];
  const updatedKeys: string[] = [];
  const mergedKeys: string[] = [];

  // Parse existing YAML
  let existing: Record<string, unknown>;
  try {
    const parsed = yaml.load(existingYaml) as Record<string, unknown>;
    if (!parsed || typeof parsed !== "object") {
      // Invalid YAML — just use generated
      return {
        merged: generated,
        warnings: ["Existing file is not valid YAML — overwriting with generated content"],
        preservedKeys: [],
        updatedKeys: Object.keys(generated),
        mergedKeys: [],
      };
    }
    existing = parsed;
  } catch {
    return {
      merged: generated,
      warnings: ["Existing file could not be parsed — overwriting with generated content"],
      preservedKeys: [],
      updatedKeys: Object.keys(generated),
      mergedKeys: [],
    };
  }

  // Start with generated as the base
  const merged: Record<string, unknown> = { ...generated };

  // Process existing keys
  for (const key of Object.keys(existing)) {
    const existingValue = existing[key];
    const generatedValue = generated[key];

    if (PRESERVE_FIELDS.includes(key)) {
      // Preserve if it has meaningful (non-default) content
      if (!isDefaultContent(existingValue)) {
        merged[key] = existingValue;
        preservedKeys.push(key);
        // Warn if generated also has content
        if (generatedValue !== undefined && !isDefaultContent(generatedValue)) {
          warnings.push(`Preserved human-edited "${key}" (generated value was different)`);
        }
      } else if (existingValue !== undefined) {
        // Existing has default content — use generated if available, otherwise keep existing
        if (generatedValue !== undefined && !isDefaultContent(generatedValue)) {
          merged[key] = generatedValue;
          updatedKeys.push(key);
        } else {
          merged[key] = existingValue;
        }
      }
    } else if (UPDATE_FIELDS.includes(key)) {
      // Always overwrite with generated (mechanical)
      if (generatedValue !== undefined) {
        merged[key] = generatedValue;
        updatedKeys.push(key);
      } else {
        // Generated doesn't have this update field — keep existing
        merged[key] = existingValue;
      }
    } else if (MERGE_FIELDS.includes(key)) {
      // Additive merge: preserve existing keys, add new ones from generated
      if (typeof existingValue === "object" && existingValue !== null && !Array.isArray(existingValue)) {
        if (typeof generatedValue === "object" && generatedValue !== null && !Array.isArray(generatedValue)) {
          merged[key] = { ...(existingValue as Record<string, unknown>), ...(generatedValue as Record<string, unknown>) };
          mergedKeys.push(key);
        } else if (generatedValue === undefined) {
          merged[key] = existingValue;
        } else {
          merged[key] = generatedValue;
          updatedKeys.push(key);
        }
      } else {
        // Non-object merge field — keep generated
        merged[key] = generatedValue !== undefined ? generatedValue : existingValue;
      }
    } else if (!(key in generated)) {
      // Key exists in existing but not in generated — preserve it (human-added)
      merged[key] = existingValue;
      preservedKeys.push(key);
    }
    // If key is in both existing and generated and not in any special category,
    // generated already wins (since we started with generated as base)
  }

  // Add any keys from generated that weren't in existing
  for (const key of Object.keys(generated)) {
    if (!(key in existing)) {
      // New field — already in merged from generated base
      updatedKeys.push(key);
    }
  }

  return {
    merged,
    warnings,
    preservedKeys,
    updatedKeys,
    mergedKeys,
  };
}

/**
 * Simple skip behavior — current default behavior.
 * Returns false to indicate "skip this file" if it exists.
 */
export function shouldSkipExisting(outputPath: string, force: boolean): boolean {
  return !force;
}
